name: JR GitLint

on: [push, pull_request]

jobs:                                                                            
  gitlint:                                                                       
                                                                                 
    runs-on: ubuntu-latest                                                       
                                                                                 
    container:                                                                   
      image: jorisroovers/gitlint                                                
                                                                                 
    steps:                                                                       
    - uses: actions/checkout@v2                                                  
    - name: git fetch                                                              
      run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: git show
      run: |
          git branch
          echo "====="
          git branch -a
          echo "====="
#         git show
#         git show ${GITHUB_HEAD_REF}  
#         git show origin/${GITHUB_BASE_REF}
    - name: run gitlint                                                          
      run: gitlint --commits origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF}  
    - run: echo "Job status is ${{ job.status }}." 

#     run: gitlint --commits origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF}  
